### ISSUE TITLE
🐛 [Bug] import torch_tensorrt error in docker

### ISSUE THREAD

**Issue by zhaozhiming37** [pytorch/TensorRT#1380]
## To Reproduce

1. `import torch_tensorrt`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-291a947ced8e>", line 1, in <module>
    import torch_tensorrt
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/__init__.py", line 85, in <module>
    from torch_tensorrt._compile import *
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: /usr/local/lib/python3.8/dist-packages/torch_tensorrt/lib/libtorchtrt.so: undefined symbol: _ZN3c1021getCustomClassTypeMapEv
```

## Expected behavior

no error

## Environment

`docker build --build-arg BASE=22.08 -f docker/Dockerfile -t torch_tensorrt:latest .`

**Comment by ZZM37** [comment]
Is there any update for the issue?

**Comment by narendasan** [comment]
Try using the latest docker file. reopen if there are still issues

**Comment by peri044** [comment]
Latest docker file : https://github.com/pytorch/TensorRT/tree/release/1.3/docker
