### ISSUE TITLE
🐛 [Bug] Unable to load torchscript model generated from tensorrt

### ISSUE THREAD

**Issue by theja-vanka** [pytorch/TensorRT#1567]
##  Bug Description

```
Traceback (most recent call last):
  File "trt_optimised_file.py", line 25, in <module>
    unet = torch.jit.load('./onnxdata/unet_v1_4_fp16_pytorch_sim.ts')
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown type name '__torch__.torch.classes.tensorrt.Engine':
  File "code/__torch__.py", line 4
  __parameters__ = []
  __buffers__ = []
  __torch___tensorrt_engine_mod_0x7ffee4094780_engine_ : __torch__.torch.classes.tensorrt.Engine
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  def forward(self_1: __torch__.tensorrt_engine_mod_0x7ffee4094780,
    input_0: Tensor,
```

Unable to load tensortrt converted to torchscript file using jit.
## To Reproduce

1. Followed the enclosed guide as is.
2. https://www.photoroom.com/tech/stable-diffusion-25-percent-faster-and-save-seconds/

## Expected behavior
Load the torch script for inference.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.2.0a0
 - PyTorch Version (e.g. 1.0):1.13.0a0+d321be6
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Docker Image: nvcr.io/nvidia/pytorch:22.08-py3, Host : Debian GNU/Linux 10 (buster)
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: local sources
 - Python version: 3.8.13
 - CUDA version: cuda_11.7.r11.7/compiler.31442593_0
 - GPU models and configuration: NVIDIA A100-SXM
 - Any other relevant information:

**Comment by theja-vanka** [comment]
Was able to resolve by adding 
```
import torch_tensorrt
```
