### ISSUE TITLE
🐛 [Bug] PixelShuffle with dynamic shape error

### ISSUE THREAD

**Issue by ivan94fi** [pytorch/TensorRT#1568]
##  Bug Description

Trying to convert a model with pixel shuffle and dynamic shape results in many errors, with this message `reshape dimension with more than one -1 wildcard`.

Converting the model with a static shape works fine.

## To Reproduce
Steps to reproduce the error:
1. Use a model with a `nn.PixelShuffle` layer
2. Use a `torch_tensorrt.Input` with `min_shape`, `opt_shape` and `max_shape`
3. Try to convert with `torch_tensorrt.compile`

To reproduce the error use the following code and execute the with `dynamic` as input:
```shell
python pixel_shuffle_bug.py dynamic
```

### Example code

```python
# Save as pixel_shuffle_bug.py
import torch
import torch.nn as nn
import torch_tensorrt


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.shuffle = nn.PixelShuffle(2)

    def forward(self, x):
        return self.shuffle(self.conv(x))


@torch.no_grad()
def main(shape_mode):
    input_data = torch.rand(1, 3, 1280, 720)
    factory_kwargs = {"dtype": torch.float32, "device": torch.device("cuda:0")}

    precision = torch.float32
    x = input_data.to(**factory_kwargs)

    m = MyModel().to(**factory_kwargs)
    m = m.eval()
    out = m(x)

    sm = torch.jit.trace(m, example_inputs=(x,))
    sout = sm(x)

    if shape_mode == "dynamic":
        inputs = [
            torch_tensorrt.Input(
                min_shape=[1, 3, 852, 480],
                opt_shape=[1, 3, 1280, 720],
                max_shape=[1, 3, 3840, 2160],
                dtype=factory_kwargs["dtype"],
            )
        ]
    else:
        inputs = [
            torch_tensorrt.Input(
                shape=[1, 3, 1280, 720],
                dtype=factory_kwargs["dtype"],
            )
        ]
    torch_tensorrt.logging.set_is_colored_output_on(True)
    with torch_tensorrt.logging.warnings():
        compile_spec = {
            "ir": "ts",
            "inputs": inputs,
            "enabled_precisions": {precision},
            "truncate_long_and_double": False,
            "require_full_compilation": True,
        }
        trtm = torch_tensorrt.compile(sm, **compile_spec)

    print("\033[92m" + "=========== Model converted ===========" + "\033[0m")

    trtout = trtm(x)

    print(f"greatest difference trt ({precision}): {(out - trtout).max().item()}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("shape_mode", choices=["dynamic", "static"])

    args = parser.parse_args()
    main(args.shape_mode)
```

### Error messages and stack traces
```
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1872] Error Code 4: Miscellaneous (IShuffleLayer (Unnamed Layer* 1) [Shuffle]: reshape dimension with more than one -1 wildcard. Reshaping [1,16,(# 2 (SHAPE input_0)),(# 3 (SHAPE input_0))] to [1,4,2,2,-1,-1].)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1872] Error Code 4: Miscellaneous (IShuffleLayer (Unnamed Layer* 1) [Shuffle]: reshape dimension with more than one -1 wildcard. Reshaping [1,16,(# 2 (SHAPE input_0)),(# 3 (SHAPE input_0))] to [1,4,2,2,-1,-1].)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1872] Error Code 4: Miscellaneous (IShuffleLayer (Unnamed Layer* 1) [Shuffle]: reshape dimension with more than one -1 wildcard. Reshaping [1,16,(# 2 (SHAPE input_0)),(# 3 (SHAPE input_0))] to [1,4,2,2,-1,-1].)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1872] Error Code 4: Miscellaneous (IShuffleLayer (Unnamed Layer* 1) [Shuffle]: reshape dimension with more than one -1 wildcard. Reshaping [1,16,(# 2 (SHAPE input_0)),(# 3 (SHAPE input_0))] to [1,4,2,2,-1,-1].)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: (Unnamed Layer* 1) [Shuffle]: at most one dimension may be inferred
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [network.cpp::validate::2991] Error Code 4: Internal Error (Layer (Unnamed Layer* 1) [Shuffle] failed validation)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
Traceback (most recent call last):
  File "pixelshuffle_dynamic_shape_error.py", line 72, in <module>
    main(args.shape_mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "pixelshuffle_dynamic_shape_error.py", line 56, in main
    trtm = torch_tensorrt.compile(sm, **compile_spec)
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/conversionctx/ConversionCtx.cpp:169] Building serialized network failed in TensorRT
```

## Expected behavior

The model should be converted with dynamic shape support.

## Environment

The official NVIDIA Pytorch Docker image version 22.12 is used.

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.3.0a0
 - PyTorch Version (e.g. 1.0): 1.14.0a0+410ce96
 - CPU Architecture: AMD64
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): preinstalled in the Docker image
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.10
 - CUDA version: 12.0
 - GPU models and configuration: NVIDIA GeForce RTX 2080 Ti, driver version 525.60.11
 - Any other relevant information:

**Comment by peri044** [comment]
We are aware of this limitation. Currently we don't have support for dynamic shape with aten::size (which gets passed to aten::reshape resulting in multiple wildcard dimensions). We plan to address this as a part of https://github.com/pytorch/TensorRT/issues/1562

**Comment by ivan94fi** [comment]
Sorry this was closed by the bot, but I received no update. Is is really important for us to have dynamic shapes with pixel shuffle. Is someone working on #1577 ?

@peri044 

Thank you

**Comment by Feynman1999** [comment]
any update on this issue?
