### ISSUE TITLE
🐛 [Bug] "symbolically traced variables cannot be used as inputs to control flow" error on nn.InstanceNorm2d

### ISSUE THREAD

**Issue by HolyWu** [pytorch/TensorRT#1620]
##  Bug Description

```
Traceback (most recent call last):
  File "C:\Users\Holy Wu\Downloads\test.py", line 21, in <module>
    trt_mod = compile(mod, [input], min_acc_module_size=1, explicit_batch_dimension=True, dynamic_batch=False)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\lower.py", line 86, in compile
    return lowerer(module, input)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\lower.py", line 322, in __call__
    return do_lower(module, inputs)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\passes\pass_utils.py", line 118, in pass_with_validation
    processed_module = pass_(module, input, *args, **kwargs)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\lower.py", line 319, in do_lower
    lower_result = pm(module)
  File "C:\Python310\lib\site-packages\torch\fx\passes\pass_manager.py", line 240, in __call__
    out = _pass(out)
  File "C:\Python310\lib\site-packages\torch\fx\passes\pass_manager.py", line 240, in __call__
    out = _pass(out)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\passes\lower_pass_manager_builder.py", line 68, in wrapped_fn
    return fn(gm, input)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\lower.py", line 247, in <lambda>
    trace_func=lambda module, inputs: acc_tracer.trace(
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_tracer.py", line 667, in trace
    traced = rewriter_base_trace(mod, ast_rewriter_allow_list, leaf_module_list)
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_tracer.py", line 585, in rewriter_base_trace
    rewritten_graph, rewritten_mod = AccRewritingTracer().trace(
  File "C:\Python310\lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_tracer.py", line 309, in trace
    return super().trace(rewritten, concrete_args), rewritten
  File "C:\Python310\lib\site-packages\torch\fx\_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "C:\Users\Holy Wu\Downloads\test.py", line 12, in forward
    return self.m(x)
  File "C:\Python310\lib\site-packages\torch\fx\_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "C:\Python310\lib\site-packages\torch\fx\_symbolic_trace.py", line 434, in call_module
    return forward(*args, **kwargs)
  File "C:\Python310\lib\site-packages\torch\fx\_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python310\lib\site-packages\torch\nn\modules\instancenorm.py", line 69, in forward
    self._check_input_dim(input)
  File "C:\Python310\lib\site-packages\torch\nn\modules\instancenorm.py", line 264, in _check_input_dim
    if input.dim() not in (3, 4):
  File "C:\Python310\lib\site-packages\torch\fx\proxy.py", line 298, in __bool__
    return self.tracer.to_bool(self)
  File "C:\Python310\lib\site-packages\torch\fx\proxy.py", line 174, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

## To Reproduce

```python
import torch
from torch import nn
from torch_tensorrt.fx import compile


class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.m = nn.InstanceNorm2d(100)

    def forward(self, x):
        return self.m(x)


if __name__ == '__main__':
    device = torch.device('cuda')
    input = torch.randn(1, 100, 35, 45, dtype=torch.half, device=device)

    with torch.inference_mode():
        mod = MyModule().eval().to(device).half()
        trt_mod = compile(mod, [input], min_acc_module_size=1, explicit_batch_dimension=True, dynamic_batch=False)
```

## Expected behavior

https://pytorch.org/docs/stable/fx.html#leaf-modules says `The default set of leaf modules is the set of standard torch.nn module instances`. Why it's still traced through and produces this error?

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0): https://github.com/pytorch/TensorRT/commit/09bef46a5c5e308184f3a2a1be5c082b55878423
 - PyTorch Version (e.g. 1.0): 1.13.1+cu117
 - CPU Architecture: x64
 - OS (e.g., Linux): Windows 11
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.9
 - CUDA version: 11.7.1
 - GPU models and configuration: RTX 3050
 - Any other relevant information:

**Comment by gs-olive** [comment]
Hello - I have reproduced the error and I believe `InstanceNorm2d` is not currently supported in fx2trt, though the error does not mention this. Symbolically tracing the model with only FX works on my end:
```python
fx_only = torch.fx.symbolic_trace(mod)
fx_only(input)
##### Succeeds #####
```
Using the `TRTInterpreter` elicits a more accurate error:
```python
from torch_tensorrt.fx import TRTInterpreter
from torch_tensorrt.fx.tools.common_fx2trt import InputTensorSpec

interpreter = TRTInterpreter(fx_only, [InputTensorSpec.from_tensor(input)], explicit_batch_dimension=True)
interpreter_result = interpreter.run()

##### Results In: #####

RuntimeError: Conversion of module of type <class 'torch.nn.modules.instancenorm.InstanceNorm2d'> not currently supported!
```
Using `torch_tensorrt.fx.compile` does not show this same error. Investigating further.

**Comment by gs-olive** [comment]
Discussed with @frank-wei - the operator `InstanceNorm2d` is not supported in FX due to control flow restrictions in its implementation, and the FX snippet above only passes because it does not trace the `InstanceNorm2d` module. Specifically, the following fails:
```python
torch.fx.symbolic_trace(nn.InstanceNorm2d(100))
##### FAILS #####
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```
To use `fx2trt` in this case, a suggestion would be to use the `acc_tracer` manually with the `leaf_module_list` argument, to indicate to the trace not to go through`InstanceNorm2d`. For example:
```python
import torch_tensorrt.fx.tracer.acc_tracer.acc_tracer as acc_tracer
traced = acc_tracer.trace(mod, [input], leaf_module_list={nn.InstanceNorm2d})
traced(input)
##### SUCCEEDS #####
```
Then, if desired, a custom operation could be written to trace `nn.InstanceNorm2d` module types

**Comment by HolyWu** [comment]
Got it. Thanks.
