### ISSUE TITLE
RuntimeError: [Error thrown at core/partitioning/shape_analysis.cpp:306] Unable to process subgraph input type of at::kLong/at::kDouble, try to compile model with truncate_long_and_double enabled

### ISSUE THREAD

**Issue by TEnsorTHiru** [pytorch/TensorRT#1800]
##  Bug Description
This runtime error was thrown when I was trying to convert my pytorch model to torch-tensorrt
Scripted Model File - [LINK]()

## To Reproduce

1. Download the model and the script
2. Use them to trace the torchscript model

```
import torch_tensorrt
import torch


vqa_model = torch.jit.load("blip_ts.pth", map_location=torch.device("cuda"))
trts_module = torch_tensorrt.compile(vqa_model,  input_signature=((torch_tensorrt.Input(shape=[1,3,480,480]),  torch_tensorrt.Input(shape=[1, 7]), torch_tensorrt.Input(shape=[1, 7]))), enabled_precisions = {torch.float, torch.half})

torch.jit.save(trt_ts_module, "blip_vqa_trt.ts")
```

Error
```
WARNING: [Torch-TensorRT] - Input signature parsing is an experimental feature, behavior and APIs may change
Traceback (most recent call last):
  File "tens.py", line 6, in <module>
    trts_module = torch_tensorrt.compile(vqa_model,  input_signature=((torch_tensorrt.Input(shape=[1,3,480,480]),  torch_tensorrt.Input(shape=[1, 7]), torch_tensorrt.Input(shape=[1, 7]))), enabled_precisions = {torch.float, torch.half})
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/partitioning/shape_analysis.cpp:306] Unable to process subgraph input type of at::kLong/at::kDouble, try to compile model with truncate_long_and_double enabled
```

## Expected behavior
The model should be traced and saved in the directory

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Pytorch NGC Container version: 23.03 -py3
 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0dev0
 - PyTorch Version (e.g. 1.0): 2.0.0a0+1767026
 - CPU Architecture: AMD64
 - OS (e.g., Linux): Linux
 - Python version: 3.8.10
 - CUDA version: 12.1
 - GPU models and configuration: Tesla T4

**Comment by narendasan** [comment]
Can you add `truncate_long_and_double=True` to your settings?

**Comment by TEnsorTHiru** [comment]
@narendasan I tried it by setting that but it raises another error stating that input types used are not supported by torch tensorrt. Isn't long tensor supported by tensorrt for now?
