### ISSUE TITLE
🐛 [Bug]  prim::SetAttr[name="attn_mask"](%_11, %7869)

### ISSUE THREAD

**Issue by seoungbae-park** [pytorch/TensorRT#2051]
##  Bug Description
```
root@733f738dc4d2:/workspace# python clip-to-onnx.py 
Traceback (most recent call last):
  File "/workspace/clip-to-onnx.py", line 71, in <module>
    base_compile(model_name)
  File "/workspace/clip-to-onnx.py", line 23, in base_compile
    trt_ts_module = torch_tensorrt.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/_compile.py", line 116, in compile
    target_ir = _get_target_ir(module_type, ir)
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/_compile.py", line 70, in _get_target_ir
    raise ValueError("Unknown ir was requested")
ValueError: Unknown ir was requested
root@733f738dc4d2:/workspace# python clip-to-onnx.py 
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
DEBUG: [Torch-TensorRT] - TensorRT Compile Spec: {
    "Inputs": [
Input(min_shape=(1,3,224,224,), opt_shape=(5,3,224,224,), max_shape=(20,3,224,224,), dtype=Float, format=Contiguous/Linear/NCHW, tensor_domain=[0, 2))Input(min_shape=(1,20,), opt_shape=(5,50,), max_shape=(20,100,), dtype=Unknown data type, format=Contiguous/Linear/NCHW, tensor_domain=[0, 2))    ]
    "Enabled Precision": [Float, Half, ]
    "TF32 Disabled": 0
    "Sparsity": 0
    "Refit": 0
    "Debug": 0
    "Device":  {
        "device_type": GPU
        "allow_gpu_fallback": False
        "gpu_id": 0
        "dla_core": -1
    }

    "Engine Capability": Default
    "Num Avg Timing Iters": 1
    "Workspace Size": 0
    "DLA SRAM Size": 1048576
    "DLA Local DRAM Size": 1073741824
    "DLA Global DRAM Size": 536870912
    "Truncate long and double": 0
    "Torch Fallback":  {
        "enabled": True
        "min_block_size": 3
        "forced_fallback_operators": [
        ]
        "forced_fallback_modules": [
        ]
    }
}
DEBUG: [Torch-TensorRT] - init_compile_spec with input vector
DEBUG: [Torch-TensorRT] - Settings requested for Lowering:
    torch_executed_modules: [
    ]
Traceback (most recent call last):
  File "/workspace/clip-to-onnx.py", line 71, in <module>
    base_compile(model_name)
  File "/workspace/clip-to-onnx.py", line 23, in base_compile
    trt_ts_module = torch_tensorrt.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="attn_mask"](%_11, %7869)
```

## To Reproduce

1. built in docker nvcr.io/nvidia/pytorch:23.05-py3 
2. run python code
3.

```
def base_compile(model_name):
    model = torch.jit.load(model_name).eval()
    dummy_img = torch.randn(1, 3, 224, 224)
    dummy_text = torch.ones(1, 20).long()
    inputs = [
        torch_tensorrt.Input(
            min_shape=[1, 3, 224, 224],
            opt_shape=[5, 3, 224, 224],
            max_shape=[20, 3, 224, 224],
            dtype=torch.float,
        ),
        torch_tensorrt.Input(
            min_shape = [1, 20],
            opt_shape = [5, 50],
            max_shape = [20, 100],
        )
    ]
    enabled_precisions = {torch.float, torch.half}
    with torch_tensorrt.logging.debug():
        trt_ts_module = torch_tensorrt.compile(
            model, inputs=inputs, enabled_precisions=enabled_precisions
        )
    input_data = (dummy_img.cuda(), dummy_text.cuda())
    result = trt_ts_module(input_data)
    torch.jit.save(trt_ts_module, "trt_ts_module.ts")
```

## Expected behavior

compile should not fail. It's already scripted model

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4dev
 - PyTorch Version (e.g. 1.0):2.0
 - CPU Architecture:
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): docker
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.9
 - CUDA version: 11.7
 - GPU models and configuration: A6000
 - Any other relevant information:

**Comment by narendasan** [comment]
Are you able to share the model? Without it or a functional reproducer we cannot replicate this
