### ISSUE TITLE
🐛 [Bug] Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#2125]
##  Bug Description

```
WARNING: [Torch-TensorRT] - For input x.8, found user specified input dtype as Half, however when inspecting the graph, the input type expected was inferred to be Float
The compiler is going to use the user setting Half
This conflict may cause an error at runtime due to partial compilation being enabled and therefore
compatibility with PyTorch's data type convention is required.
If you do indeed see errors at runtime either:
- Remove the dtype spec for x.8
- Disable partial compilation by setting require_full_compilation to True
Traceback (most recent call last):
  File "export_trt.py", line 38, in <module>
    trt_ts_module = torch_tensorrt.compile(torch_script_module,
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 133, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 139, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/hat/archs/hat_arch.py", line 301, in forward
    mask = torch.to(_251, dtype=6, layout=0, device=torch.device("cpu"))
    _252 = (pos_drop).forward((patch_embed).forward(_7, ), )
    _253 = (_0).forward(relative_position_index_SA, relative_position_index_OCA, _252, _104, _202, h, w, _103, _201, _102, _200, mask, _101, _199, _100, _198, _99, _197, _98, _196, _97, _195, _96, _194, _95, _193, _94, _192, _93, _191, _92, _190, _91, _189, _90, _188, _89, _187, )
            ~~~~~~~~~~~ <--- HERE
    _254 = (_1).forward(relative_position_index_SA, relative_position_index_OCA, _253, _88, _186, h, w, _87, _185, _86, _184, mask, _85, _183, _84, _182, _83, _181, _82, _180, _81, _179, _80, _178, _79, _177, _78, _176, _77, _175, _76, _174, _75, _173, _74, _172, _73, _171, )
    _255 = (_2).forward(relative_position_index_SA, relative_position_index_OCA, _254, _72, _170, h, w, _71, _169, _70, _168, mask, _69, _167, _68, _166, _67, _165, _66, _164, _65, _163, _64, _162, _63, _161, _62, _160, _61, _159, _60, _158, _59, _157, _58, _156, _57, _155, )
  File "code/__torch__/hat/archs/hat_arch.py", line 389, in forward
    patch_unembed = self.patch_unembed
    residual_group = self.residual_group
    _260 = (residual_group).forward(rpi, rpi0, argument_3, argument_4, argument_5, h, w, argument_8, argument_9, argument_10, argument_11, mask, argument_13, argument_14, argument_15, argument_16, argument_17, argument_18, argument_19, argument_20, argument_21, argument_22, argument_23, argument_24, argument_25, argument_26, argument_27, argument_28, argument_29, argument_30, argument_31, argument_32, argument_33, argument_34, argument_35, argument_36, )
            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _261 = (patch_unembed).forward(_260, argument_37, argument_38, )
    _262 = (patch_embed).forward((conv).forward(_261, ), )
  File "code/__torch__/hat/archs/hat_arch.py", line 451, in forward
    _0 = getattr(blocks4, "0")
    _263 = (_0).forward(rpi, argument_3, argument_4, argument_5, h, w, argument_8, argument_9, )
    _264 = (_1).forward(rpi, _263, argument_10, argument_11, h, w, mask, argument_13, argument_14, )
            ~~~~~~~~~~~ <--- HERE
    _265 = (_2).forward(rpi, _264, argument_15, argument_16, h, w, argument_17, argument_18, )
    _266 = (_3).forward(rpi, _265, argument_19, argument_20, h, w, mask, argument_21, argument_22, )
  File "code/__torch__/hat/archs/hat_arch/___torch_mangle_39.py", line 57, in forward
    x_windows = torch.view(torch.contiguous(_17), [-1, 16, 16, _12])
    x2 = torch.view(x_windows, [-1, 256, _5])
    windows = torch.view((attn).forward(rpi, x2, mask, ), [-1, 16, 16, _4])
                          ~~~~~~~~~~~~~ <--- HERE
    _18 = torch.floor_divide(h, CONSTANTS.c11)
    _19 = int(_18)
  File "code/__torch__/hat/archs/hat_arch/___torch_mangle_20.py", line 55, in forward
    _18 = torch.view(attn0, _17)
    _19 = torch.unsqueeze(torch.unsqueeze(mask, 1), 0)
    attn1 = torch.add(_18, _19)
            ~~~~~~~~~ <--- HERE
    input = torch.view(attn1, [-1, 6, _4, _3])
    _20 = (attn_drop).forward((softmax).forward(input, ), )

Traceback of TorchScript, original code (most recent call last):
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(185): forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(292): forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(528): forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(619): forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(964): forward_features
/hy-tmp/HAT_torch_trt/hat/archs/hat_arch.py(978): forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/usr/local/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(1056): trace_module
/usr/local/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(794): trace
export_trt.py(79): _process
export_trt.py(111): _run
export_trt.py(115): infer
export_trt.py(166): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
## To Reproduce

here is my code:
```python

example = np.random.random((1,3,448,448))
example_tensor =torch.as_tensor(example,dtype=torch.float32)
torch_script_module = torch.jit.load("traced_model.pt").half().cuda()
trt_ts_module = torch_tensorrt.compile(torch_script_module,
    # If the inputs to the module are plain Tensors, specify them via the `inputs` argument:
    inputs = [# Provide example tensor for input shape or...
        torch_tensorrt.Input( # Specify input object with shape and dtype
            min_shape=[1, 3, 32, 32],
            opt_shape=[1, 3, 448, 448],
            max_shape=[1, 3, 448, 448],
            # For static size shape=[1, 3, 224, 224]
            dtype=torch.half) # Datatype of input tensor. Allowed options torch.(float|half|int8|int32|bool)
    ],

    # For inputs containing tuples or lists of tensors, use the `input_signature` argument:
    # Below, we have an input consisting of a Tuple of two Tensors (Tuple[Tensor, Tensor])
    # input_signature = ( (torch_tensorrt.Input(shape=[1, 3, 224, 224], dtype=torch.half),
    #                      torch_tensorrt.Input(shape=[1, 3, 224, 224], dtype=torch.half)), ),

    enabled_precisions = {torch.half}, # Run with FP16
)

result = trt_ts_module(input_data) # run inference
torch.jit.save(trt_ts_module, "32_448.ts") # save the TRT embedded Torchscript

```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0
 - PyTorch Version (e.g. 1.0):2.0.1
 - CPU Architecture: x86
 - OS (e.g., Linux): ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8 
 - CUDA version:12
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

Hello! I am trying to convert a transformer architecture model, but I don't know why I am encountering the aforementioned issue when writing it that way. If you need any additional information, please let me know and I will continue to provide it. Thank you very much.

**Comment by monk-after-90s** [comment]
How about now?
