### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT,  Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#2196]
##  Bug Description

I want to ask the reason why I can't run the torch_tensorrt export? 
I use the 'to(torch.float32)' to set some layer to torch.float32 precision, but it seems not work.
Thank you very much.

```
2023-08-14 12:06:10,690 INFO: Loading HAT model from /work/experiments/pretrained_models/Real_HAT_GAN_SRx4.pth, with param key: [params_ema].
compiler!
Traceback (most recent call last):
  File "/work/export_trt.py", line 160, in <module>
    trt_ts_module = torch_tensorrt.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 132, in compile
    ts_mod = torch.jit.script(module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 894, in compile_unbound_method
    stub = make_stub(fn, fn.__name__)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 58, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/frontend.py", line 297, in get_jit_def
    return build_def(parsed_def.ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/frontend.py", line 335, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/frontend.py", line 359, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1039
    def to(self, *args, **kwargs):
                         ~~~~~~~ <--- HERE
        r"""Moves and/or casts the parameters and buffers.
```

NGC：nvcr.io/nvidia/tensorrt:22.10-py3

**Comment by narendasan** [comment]
This is a limitation of torchscript. You cant script functions with `fn(*args, **kwargs)`

**Comment by sanbuphy** [comment]
> This is a limitation of torchscript. You cant script functions with `fn(*args, **kwargs)`

Thanks, I found that it caused by `.to(dtype=torch.float32)` , I need to set some layer return float32, Is that anyway can solve this problem?  I  found in different documentation but nothing work.

**Comment by apbose** [comment]
Could you please provide the exact command or the code snippet you used for `torch.compile` to repro the above? As metioned above torchscript would not support *args or **kwargs. Thanks!

**Comment by sanbuphy** [comment]
> Could you please provide the exact command or the code snippet you used for `torch.compile` to repro the above? As metioned above torchscript would not support *args or **kwargs. Thanks!

Hi , Here is the script I used:

```python
import torch 
import torch_tensorrt
import torch.nn as nn


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 100)
        self.fc3 = nn.Linear(100, 200)

    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        self.fc2.to(torch.float32)
        out = self.fc2(out.to(torch.float32)).half()
        out = self.fc3(out)
        return out

model = MyNet()
for param in model.parameters():
    param.data.normal_(0, 1) 
print(model)

dummy = torch.tensor([1.23123],dtype=torch.float16).cuda()

print(dummy.shape)

compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}

model.half().eval().cuda()
with torch.no_grad():
    out = model(dummy)
    traced_model = torch.jit.script(model, dummy)
    model_trt = torch_tensorrt.compile(traced_model, **compile_settings)
    print(out)
```

**Comment by apbose** [comment]
The issue is that torch.jit.script would not accept functions with *args or **kwargs. To workaround the above you could use ``torch.jit.trace` and then torch.compile(backend="ts")`  or ` torch.compile(backend="torch_compile")`.

1. First method
```
compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "ir": "ts",
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}
traced_model = model.jit.trace(model)
model_trt=torch_tensorrt.compile(traced_model, **compile_settings)
```

2. Second method
```
compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "ir": "torch_compile",
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}
model_trt=torch_tensorrt.compile(model, **compile_settings)
```

**Comment by sanbuphy** [comment]
> The issue is that torch.jit.script would not accept functions with *args or **kwargs. To workaround the above you could use `torch.jit.trace` and then `torch.compile(backend="ts")` or ` torch.compile(backend="torch_compile")`.
> 
> 1. First method
> 
> ```
> compile_settings = {
>     "inputs": [
>         torch_tensorrt.Input(
>             min_shape=[1],
>             opt_shape=[1],
>             max_shape=[1],
>             dtype=torch.half)
>     ],
>     "ir": "ts",
>     "truncate_long_and_double": True,
>     "enabled_precisions": {torch.half}  # Run with FP16
> }
> traced_model = model.jit.trace(model)
> model_trt=torch_tensorrt.compile(traced_model, **compile_settings)
> ```
> 
> 2. Second method
> 
> ```
> compile_settings = {
>     "inputs": [
>         torch_tensorrt.Input(
>             min_shape=[1],
>             opt_shape=[1],
>             max_shape=[1],
>             dtype=torch.half)
>     ],
>     "ir": "torch_compile",
>     "truncate_long_and_double": True,
>     "enabled_precisions": {torch.half}  # Run with FP16
> }
> model_trt=torch_tensorrt.compile(model, **compile_settings)
> ```

Hi , can you try it again?  I still can't use it 😢
```python
import torch 
import torch_tensorrt
import torch.nn as nn


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 100)
        self.fc3 = nn.Linear(100, 200)

    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        self.fc2.to(torch.float32)
        out = self.fc2(out.to(torch.float32)).half()
        out = self.fc3(out)
        return out

model = MyNet()
for param in model.parameters():
    param.data.normal_(0, 1) 
print(model)

dummy = torch.tensor([1.23123],dtype=torch.float16).cuda()

print(dummy.shape)

compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "ir": "torch_compile",
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}
model.half().eval().cuda()
with torch.no_grad():
    out = model(dummy)
    traced_model = torch.jit.script(model, dummy)
    model_trt = torch_tensorrt.compile(traced_model, **compile_settings)
    print(out)
```

**Comment by apbose** [comment]
Hi @sanbuphy , `torch.jit.script` would not work in this case. It is a limitation from the torchscript side. You can use `torch.jit.trace` (first method) or `torch.compile(backend= 'torch_tensorrt') (second method)`

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , `torch.jit.script` would not work in this case. It is a limitation from the torchscript side. You can use `torch.jit.trace` (first method) or `torch.compile(backend= 'torch_tensorrt')` (second method)

Sorry, I sent the wrong picture. Using the ts method works for me, but I encountered some issues when using the second method.

```python
import torch 
import torch_tensorrt
import torch.nn as nn


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 100)
        self.fc3 = nn.Linear(100, 200)

    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        self.fc2.to(torch.float32)
        out = self.fc2(out.to(torch.float32)).half()
        out = self.fc3(out).to(torch.float16)
        return out

model = MyNet()
for param in model.parameters():
    param.data.normal_(0, 1) 
print(model)

dummy = torch.tensor([1.23123],dtype=torch.float16).cuda()

print(dummy.shape)

compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "ir": "torch_compile",
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}
model.half().eval().cuda()
with torch.no_grad():
    out = model(dummy)
    traced_model = torch.jit.trace(model, dummy)
    model_trt = torch_tensorrt.compile(traced_model, **compile_settings)
    print(out)
    out2 = model_trt(dummy)
    print(out2)
```
![image](https://github.com/pytorch/TensorRT/assets/96160062/7271bbe3-9e7a-47e0-9155-c70140d39441)


by the way , can i ask what is the detail  of 'ts' ir? thank you.

**Comment by apbose** [comment]
In the second method you would not need to trace it first, since torch.compile with ir : "torch_compile" would do the tracing and compilation for you. May I know the above error shows up when? As in are you on torch TRT main or NGC release container? And also is the ir= "torch_compile"?
ir="ts" denotes the torchscript intermediate representation. At present the ir type supported is ts, fx, dynamo and torch_compile.

**Comment by sanbuphy** [comment]
> In the second method you would not need to trace the model first, since torch.compile with ir : "torch_compile" would do the tracing and compilation for you. May I know the above error shows up when? As in are you on torch TRT main or NGC release container? And also is the ir= "torch_compile"? ir="ts" denotes the torchscript intermediate representation. At present the ir type supported is ts, fx, dynamo and torch_compile.

Hi , Thank you for your reply, I meet the error when i use it in my local virtual envrionment. I install the torch_tensorrt and  tensorrt pypi package.

Here is my code:( I cancel the model trace but it also doesn't work)

```cpp
import torch 
import torch_tensorrt
import torch.nn as nn


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 100)
        self.fc3 = nn.Linear(100, 200)

    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        self.fc2.to(torch.float32)
        out = self.fc2(out.to(torch.float32)).half()
        out = self.fc3(out).to(torch.float16)
        return out

model = MyNet()
for param in model.parameters():
    param.data.normal_(0, 1) 
print(model)

dummy = torch.tensor([1.23123],dtype=torch.float16).cuda()

print(dummy.shape)

compile_settings = {
    "inputs": [
        torch_tensorrt.Input(
            min_shape=[1],
            opt_shape=[1],
            max_shape=[1],
            dtype=torch.half)
    ],
    "ir": "torch_compile",
    # "ir": "ts",
    "truncate_long_and_double": True,
    "enabled_precisions": {torch.half}  # Run with FP16
}
model.half().eval().cuda()
with torch.no_grad():
    out = model(dummy)
    # traced_model = torch.jit.trace(model, dummy)
    model_trt = torch_tensorrt.compile(model, **compile_settings)
    print(out)
    out2 = model_trt(dummy)
    print(out2)
```

**Comment by apbose** [comment]
Hi @sanbuphy can you instead use `docker pull ghcr.io/pytorch/tensorrt/torch_tensorrt:main` The above passes in that container

**Comment by sanbuphy** [comment]
> Hi @sanbuphy can you instead use `docker pull ghcr.io/pytorch/tensorrt/torch_tensorrt:main` The above passes in that container

Thank you very much , It works well.
