### ISSUE TITLE
🐛 [Bug] Fail to compile BERT with dynamic sequence length

### ISSUE THREAD

**Issue by Njuapp** [pytorch/TensorRT#2294]
##  Bug Description

Torch-TensorRT fails to compile BERT with dynamic seqlen config.

```bash
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::processCheck::862] Error Code 4: Internal Error (%33 : Tensor = aten::add(%embeddings.1, %position_embeddings.1, %1155), scope: __module.bert/__module.bert.embeddings # /usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py:238:0: dimensions not compatible for elementwise.)
Traceback (most recent call last):
  File "/workspace/torchtrt-issues/main.py", line 32, in <module>
    trt_model = torch_tensorrt.compile(traced_mlm_model,
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/_compile.py", line 133, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/ts/_compiler.py", line 139, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/conversionctx/ConversionCtx.cpp:169] Building serialized network failed in TensorRT
```

## To Reproduce

```python
from transformers import BertTokenizer, BertForMaskedLM
import torch
import timeit
import time
import numpy as np
import torch_tensorrt
import torch.backends.cudnn as cudnn
enc = BertTokenizer.from_pretrained('hfl/chinese-roberta-wwm-ext')
batch_size = 4
batched_indexed_tokens = [[101, 16]*16]*batch_size
batched_segment_ids = [[0, 0]*16]*batch_size
batched_attention_masks = [[0, 0]*16]*batch_size
tokens_tensor = torch.tensor(batched_indexed_tokens)
segments_tensor = torch.tensor(batched_segment_ids)
attention_masks_tensor = torch.tensor(batched_attention_masks)
mlm_model_ts = BertForMaskedLM.from_pretrained('hfl/chinese-roberta-wwm-ext', torchscript=True)
traced_mlm_model = torch.jit.trace(mlm_model_ts, [tokens_tensor, segments_tensor, attention_masks_tensor])

new_level = torch_tensorrt.logging.Level.Debug
torch_tensorrt.logging.set_reportable_log_level(new_level)
traced_mlm_model.cuda()

# trt_model = torch_tensorrt.compile(traced_mlm_model, 
#     inputs= [torch_tensorrt.Input(shape=[batch_size, 32], dtype=torch.int32),  # input_ids
#              torch_tensorrt.Input(shape=[batch_size, 32], dtype=torch.int32),  # token_type_ids
#              torch_tensorrt.Input(shape=[batch_size, 32], dtype=torch.int32)], # attention_mask
#     enabled_precisions= {torch.half}, # Run with 16-bit precision
#     workspace_size=2000000000,
#     truncate_long_and_double=True
# )

trt_model = torch_tensorrt.compile(traced_mlm_model, 
inputs= [torch_tensorrt.Input(min_shape=(batch_size, 8),opt_shape=(batch_size, 16),max_shape=(batch_size, 128), dtype=torch.int32),  # input_ids
            torch_tensorrt.Input(min_shape=(batch_size, 8),opt_shape=(batch_size, 16),max_shape=(batch_size, 128), dtype=torch.int32),  # token_type_ids
            torch_tensorrt.Input(min_shape=(batch_size, 8),opt_shape=(batch_size, 16),max_shape=(batch_size, 128), dtype=torch.int32)], # attention_mask
enabled_precisions= {torch.float32}, 
# workspace_size=1 << 33,
truncate_long_and_double=True
)


torch.jit.save(trt_model, "trt_torchscript_module.ts") # save the TRT embedded Torchscript
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0
 - PyTorch Version (e.g. 1.0): 2.0.1+cu118
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zewenli98** [comment]
@peri044

**Comment by zidong-onepiece1** [comment]
same problem, Has it been resolved?
