### ISSUE TITLE
🐛 [Bug] getitem node does not have meta data  

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#2478]
##  Bug Description

All export serde tests fail with the following error due to some changes in the nightly
```
exp_program = create_trt_exp_program(patched_module)
  File "/home/dperi/Downloads/TensorRT/py/torch_tensorrt/dynamo/_exporter.py", line 246, in create_trt_exp_program
    trt_exp_program = ExportedProgram(
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/export/exported_program.py", line 129, in __init__
    self.verifier().check(self)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 126, in check
    self._check_graph_module(ep.graph_module)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 183, in _check_graph_module
    _check_val(node)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 57, in _check_val
    raise SpecViolationError(f"Node.meta {node.name} is missing val field.")
```

## To Reproduce

In our test suite, python -m pytest test_export_serde.py

## Expected behavior

Export serde should work properly

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peri044** [comment]
If we add the trt_node's meta data to getitem, we face a new error 
```
trt_exp_program = ExportedProgram(
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/export/exported_program.py", line 129, in __init__
    self.verifier().check(self)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 135, in check
    raise e
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 129, in check
    _verify_exported_program_signature(ep)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_export/verifier.py", line 335, in _verify_exported_program_signature
    raise SpecViolationError(
torch._export.verifier.SpecViolationError: User output getitem is not in the correct order or is not found in the exported program's user_output list: ('output',).
```

**Comment by peri044** [comment]
Once we modify the output to be getitem in create_trt_exp_program, we get an error in deserialization (torch.export.load) 
input_nodes = [node for node in gm.graph.nodes if node.op == "placeholder"]
output_nodes = [node for node in gm.graph.nodes if node.name == "getitem"]
```
Traceback (most recent call last):
  File "/home/dperi/Downloads/TensorRT/tests/py/dynamo/models/test_export_serde.py", line 64, in <module>
    test_base_full_compile("dynamo")
  File "/home/dperi/Downloads/TensorRT/tests/py/dynamo/models/test_export_serde.py", line 49, in test_base_full_compile
    deserialized_prog = deserialize(*serialized_prog)
TypeError: torch._export.serde.serialize.deserialize() argument after * must be an iterable, not SerializedArtifact
```

**Comment by peri044** [comment]
This is resolved with the latest fixes on export_2.2 branch

**Comment by DefTruth** [comment]
got the same error with torch_tensorrt 2.2.0
```bash 
torch._export.verifier.SpecViolationError: Node.meta max_pool2d_default is missing val field.
```
