### ISSUE TITLE
🐛 [Bug] Encountered bug when installing Torch-TensorRT 

### ISSUE THREAD

**Issue by Rasantis** [pytorch/TensorRT#2484]
im on a windows machine using python 3.11.4, i did all the steps, like in this tutorial:
https://medium.com/@peiyuan67/ai-inference-clear-steps-to-install-tensorrt-on-windows-d13f49d2f18b
when trying to install tensor rt lib, i got this error:
pip install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases        
Looking in links: https://github.com/NVIDIA/Torch-TensorRT/releases
Collecting torch-tensorrt
  Using cached torch-tensorrt-0.0.0.post1.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-0p7um8yy\torch-tensorrt_a7c52e0737e94e34a21ac47411265686\setup.py", line 125, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      To install Torch-TensorRT please run the following command:

      $ pip install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

im using cuda 12.1

**Comment by phineas-pta** [comment]
`pip install torch-tensorrt` only available on linux

on windows u must build from source
