### ISSUE TITLE
❓ [Question] Error regarding the operation of pytorch_quantization：/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by tms2003** [pytorch/TensorRT#2551]
## ❓ Question

When I run finetune_qat.py for vgg  I get the error:

```
python finetune_qat.py 
Traceback (most recent call last):
  File "/home/incar/tms/source/tensortclassicify/finetune_qat.py", line 16, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/__init__.py", line 20, in <module>
    from .quant_modules import *
  File "/home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/quant_modules.py", line 23, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/nn/__init__.py", line 19, in <module>
    from pytorch_quantization.nn.modules.tensor_quantizer import *
  File "/home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 24, in <module>
    from pytorch_quantization.tensor_quant import QuantDescriptor, tensor_quant, fake_tensor_quant, scaled_e4m3
  File "/home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/tensor_quant.py", line 28, in <module>
    from pytorch_quantization import cuda_ext
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/incar/miniconda3/envs/timm/lib/python3.10/site-packages/pytorch_quantization/cuda_ext.cpython-310-x86_64-linux-gnu.so)
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 '2.1.2+cu121'
 - CPU Architecture:
 intel 
 - OS (e.g., Linux):
 ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 pip install torch torchvision torchaudio
 - Build command you used (if compiling from source):
 pip install nvidia-pyindex sphinx-glpi-theme prettytable pyyaml absl-py scipy
pip install -i https://pypi.ngc.nvidia.com pytorch-quantization
 - Are you using local sources or building from archives:
 no
 - Python version:
 3.10
 - CUDA version:
 12.2
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

so,how can i run pytorch_quantization?

**Comment by peri044** [comment]
From the error log, it looks like some system version issues. 
Can you try building and installing pytorch-quantization toolkit from source ? https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/pytorch-quantization#pytorch-quantization 
If that doesn't work, please post this issue at https://github.com/NVIDIA/TensorRT/issues

**Comment by peri044** [comment]
Ah it looks like the same issue has been filed https://github.com/NVIDIA/TensorRT/issues/3666#issuecomment-1944178324 and building from source works.
