### ISSUE TITLE
RuntimeError:  Variable 'x' previously had type Tensor but is now being assigned to a value of type List[Tensor]

### ISSUE THREAD

**Issue by dizhenx** [pytorch/TensorRT#2556]
Load checkpoint from: wav2lip_checkpoint/checkpoint_step002680000.pth
  0%|                                                                                                                                                                                           | 0/22 [01:37<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 291, in <module>
    main()
  File "inference.py", line 261, in main
    model = torch_tensorrt.compile(model,inputs=[torch_tensorrt.Input((64, 3, 288, 288), dtype=torch.half)],
  File "/mnt/data/creative/miniconda3/envs/Wav2Lip3.8/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 132, in compile
    ts_mod = torch.jit.script(module)
  File "/mnt/data/creative/miniconda3/envs/Wav2Lip3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "/mnt/data/creative/miniconda3/envs/Wav2Lip3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/mnt/data/creative/miniconda3/envs/Wav2Lip3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/mnt/data/creative/miniconda3/envs/Wav2Lip3.8/lib/python3.8/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Variable 'x' previously had type Tensor but is now being assigned to a value of type List[Tensor]
:
  File "/mnt/data/creative/wav2lip_288x288_288/models/wav2lipv2.py", line 143
            #x = torch.split(x, B, dim=0) # [(B, C, H, W)]
            print(x)
            x = torch.split(x, split_size=B, dim=0) # [(B, C, H, W)]
            ~ <--- HERE
            #x = torch.chunk(x, B, dim=0) # [(B, C, H, W)]
            print(x)
  
  How to solve the error?
  my code is below:
  model = torch_tensorrt.compile(
    model,
    inputs=[torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.half)],
    enabled_precisions={torch.half},  # 使用FP16
    workspace_size=1 << 22
)

**Comment by gs-olive** [comment]
Hi - this appears to be an issue during scripting of the model with `torch.jit.script(module)`. Could you try `ts_model = torch.jit.script(model)` to see if the model can be scripted to TorchScript first? If that fails, the model might be traceable with `ts_model = torch.jit.trace(model, inputs)`, then `ts_model` can be passed into `torch_tensorrt.compile`.

Please also share the versions of Torch and Torch-TensorRT you are using.
