### ISSUE TITLE
🐛 [Bug] SerializeError when save a ExportedProgram using python runtime

### ISSUE THREAD

**Issue by HolyWu** [pytorch/TensorRT#2652]
## To Reproduce

```py
import torch
import torch_tensorrt
import torchvision.models as models

model = models.resnet18(pretrained=True).eval().cuda().half()
inputs = [torch.randn((1, 3, 224, 224), dtype=torch.half, device="cuda")]

optimized_model = torch_tensorrt.compile(
    model,
    ir="dynamo",
    inputs=inputs,
    enabled_precisions={torch.half},
    min_block_size=1,
    use_python_runtime=True,
    output_format="exported_program",
)

torch.export.save(optimized_model, "trt_model.ep")
```

```
holy@HolyWu:~/TensorRT/examples/dynamo$ python3 test.py
/home/holy/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/holy/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
INFO:torch_tensorrt.dynamo._compiler:Compilation Settings: CompilationSettings(precision=torch.float16, debug=False, workspace_size=0, min_block_size=1, torch_executed_ops=set(), pass_through_build_failures=False, max_aux_streams=None, version_compatible=False, optimization_level=None, use_python_runtime=True, truncate_long_and_double=False, use_fast_partitioner=True, enable_experimental_decompositions=False, device=Device(type=DeviceType.GPU, gpu_id=0), require_full_compilation=False, disable_tf32=False, sparse_weights=False, refit=False, engine_capability=<EngineCapability.DEFAULT: 0>, num_avg_timing_iters=1, dla_sram_size=1048576, dla_local_dram_size=1073741824, dla_global_dram_size=536870912, dryrun=False, hardware_compatible=False, output_format='exported_program')

INFO:torch_tensorrt.dynamo.conversion._TRTInterpreter:TRT INetwork construction elapsed time: 0:00:00.121588
[02/22/2024-17:15:01] [TRT] [W] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[02/22/2024-17:15:01] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[02/22/2024-17:15:01] [TRT] [W] Check verbose logs for the list of affected weights.
[02/22/2024-17:15:01] [TRT] [W] - 1 weights are affected by this issue: Detected subnormal FP16 values.
INFO:torch_tensorrt.dynamo.conversion._TRTInterpreter:Build TRT engine elapsed time: 0:00:11.183447
INFO:torch_tensorrt.dynamo.conversion._TRTInterpreter:TRT Engine uses: 2408448 bytes of Memory
/home/holy/.local/lib/python3.10/site-packages/torch/export/exported_program.py:737: UserWarning: Unable to execute the generated python source code from the graph. The graph module will no longer be directly callable, but you can still run the ExportedProgram, and if needed, you can run the graph module eagerly using torch.fx.Interpreter.
  warnings.warn(
Traceback (most recent call last):
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 1071, in serialize_graph
    getattr(self, f"handle_{node.op}")(node)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 437, in handle_call_function
    inputs=self.serialize_inputs(node.target, node.args, node.kwargs),
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 530, in serialize_inputs
    arg=self.serialize_input(args[i]),
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 724, in serialize_input
    raise SerializeError(f"Unsupported argument type: {type(arg)}")
torch._export.serde.serialize.SerializeError: Unsupported argument type: <class 'tensorrt_bindings.tensorrt.ICudaEngine'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/holy/TensorRT/examples/dynamo/test.py", line 18, in <module>
    torch.export.save(optimized_model, "trt_model.ep")
  File "/home/holy/.local/lib/python3.10/site-packages/torch/export/__init__.py", line 256, in save
    save(ep, f, extra_files=extra_files, opset_version=opset_version)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/__init__.py", line 238, in save
    artifact: SerializedArtifact = serialize(ep, opset_version)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 1894, in serialize
    ExportedProgramSerializer(opset_version).serialize(exported_program)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 1116, in serialize
    serialized_graph_module = gm_serializer.serialize(exported_program.graph_module)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 1087, in serialize
    graph = self.serialize_graph(graph_module)
  File "/home/holy/.local/lib/python3.10/site-packages/torch/_export/serde/serialize.py", line 1073, in serialize_graph
    raise SerializeError(f"Failed serializing node {node} in graph: {node.format_node()}") from e
torch._export.serde.serialize.SerializeError: Failed serializing node execute_engine_default in graph: %execute_engine_default : [num_users=1] = call_function[target=torch.ops.tensorrt.execute_engine.default](args = ((%arg122_1,), <tensorrt_bindings.tensorrt.ICudaEngine object at 0x7fd9b3054270>), kwargs = {})
```

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0): https://github.com/pytorch/TensorRT/commit/afd5abebbffa49107bcc7766c9f00bd6be2e593c
 - PyTorch Version (e.g. 1.0): 2.3.0.dev20240221+cu121
 - CPU Architecture: x64
 - OS (e.g., Linux): Ubuntu 22.04 LTS
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.12
 - CUDA version: 12.1
 - GPU models and configuration: RTX 3050
 - Any other relevant information:

**Comment by peri044** [comment]
@HolyWu Thanks for filing the bug. We do not support serializing ExportedPrograms via python runtime. I shall update the documentation. Can you use C++ runtime instead (`use_python_runtime=False`) ?
