### ISSUE TITLE
Can not compile on cuda:1 on multi-gpus 

### ISSUE THREAD

**Issue by alibool** [pytorch/TensorRT#2668]
The following code works well with 'cuda:0', but will raise error when use 'cuda:1'
```
import torch
from torchvision import models
import torch_tensorrt


dtype = torch.float32
# works fine when cuda:0 but error on cuda:1
device = torch.device("cuda:0")

model = models.resnet50().to(dtype).to(device)
model.eval()
inputs_1 = torch.rand(12, 3, 224, 224).to(device).to(dtype)

optimized_model = torch.compile(model, backend="torch_tensorrt", dynamic=False, fullgraph=True,
                                options={
                                    "precision": dtype,
                                    "device": device
                                })

with torch.no_grad():
    useless = optimized_model(inputs_1)
print(useless)
```
Two gpus are both A100, pytorch 2.2.1 cu118 torch-tensorrt 2.2.0+cu118 tensorrt 8.6.0

**Comment by gs-olive** [comment]
Hi - thanks for the report - could you share the error logs when compiling with `cuda:1`, preferably with `debug=True`?

**Comment by gs-olive** [comment]
As an update on this, I am seeing the following output when running your script:
```
ERROR: [Torch-TensorRT] - 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
ERROR: [Torch-TensorRT] - 1: [defaultAllocator.cpp::deallocate::61] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
```
It seems to appear because the active CUDA device in the context is being overwritten or incorrectly set. I am looking into the issue. For a temporary workaround, consider using the prefix argument `CUDA_VISIBLE_DEVICES=1` when running the script, to have `cuda:1` act as `cuda:0` from within the script

**Comment by gs-olive** [comment]
I have some additional details to share on this, as well as the proposed fix.

In the initial code, the `device` parameter was set to `"cuda:1"`, but the _ambient_ active CUDA device in the thread was the default (`"cuda:0"`). In order to have the active thread use `"cuda:1"`, it is necessary to add the line `device = torch.device("cuda:1"); torch.cuda.set_device(device)` before compilation. This makes the compilation and inference functional on my end.

If the intended usecase was to compile/run on multiple GPUs, I would suggest using separate Python threads, each with a `set_device` call to ensure the ambient device in that thread is the intended one. Alternatively, you could enable `torch_tensorrt.runtime.set_multi_device_safe_mode(True)` - see below.

We recently added a feature, Multi-Device Runtime Safety, which gives more verbose messages regarding device contexts and will automatically switch devices if a mismatch is detected, at the cost of runtime device-checking. This can be enabled via `torch_tensorrt.runtime.set_multi_device_safe_mode(True)`. The default is `False`.

This code works on my end, please let me know if it also resolves your case:
```python
import torch
from torchvision import models
import torch_tensorrt


dtype = torch.float32
device = torch.device("cuda:1")
torch.cuda.set_device(device)

model = models.resnet50().to(dtype).to(device)
model.eval()
inputs_1 = torch.rand(12, 3, 224, 224).to(device).to(dtype)

optimized_model = torch.compile(model, backend="torch_tensorrt", dynamic=False, fullgraph=True,
                                options={
                                    "precision": dtype,
                                    "device": device
                                })

with torch.no_grad():
    useless = optimized_model(inputs_1)
print(useless)
```

**Comment by alibool** [comment]
Thanks

> I have some additional details to share on this, as well as the proposed fix.
> 
> In the initial code, the `device` parameter was set to `"cuda:1"`, but the _ambient_ active CUDA device in the thread was the default (`"cuda:0"`). In order to have the active thread use `"cuda:1"`, it is necessary to add the line `device = torch.device("cuda:1"); torch.cuda.set_device(device)` before compilation. This makes the compilation and inference functional on my end.
> 
> If the intended usecase was to compile/run on multiple GPUs, I would suggest using separate Python threads, each with a `set_device` call to ensure the ambient device in that thread is the intended one. Alternatively, you could enable `torch_tensorrt.runtime.set_multi_device_safe_mode(True)` - see below.
> 
> We recently added a feature, Multi-Device Runtime Safety, which gives more verbose messages regarding device contexts and will automatically switch devices if a mismatch is detected, at the cost of runtime device-checking. This can be enabled via `torch_tensorrt.runtime.set_multi_device_safe_mode(True)`. The default is `False`.
> 
> This code works on my end, please let me know if it also resolves your case:
> 
> ```python
> import torch
> from torchvision import models
> import torch_tensorrt
> 
> 
> dtype = torch.float32
> device = torch.device("cuda:1")
> torch.cuda.set_device(device)
> 
> model = models.resnet50().to(dtype).to(device)
> model.eval()
> inputs_1 = torch.rand(12, 3, 224, 224).to(device).to(dtype)
> 
> optimized_model = torch.compile(model, backend="torch_tensorrt", dynamic=False, fullgraph=True,
>                                 options={
>                                     "precision": dtype,
>                                     "device": device
>                                 })
> 
> with torch.no_grad():
>     useless = optimized_model(inputs_1)
> print(useless)
> ```

Thanks, when will be this nice feature released and should I close this issue?

**Comment by gs-olive** [comment]
Hi - this feature should already be in the version you are using. Once you have verified the resolution works for you, feel free to close this bug and open a new one if there are other issues.

**Comment by orioninthesky98** [comment]
hi @gs-olive  this error is back . i remember being able to fix it using `torch.cuda.set_device("cuda:1")` , but now it doesn't work anymore... I'm on `torch_tensorrt.__version__ == 2.6.0` 

```Traceback (most recent call last):
  File "/home/mlin/repos/lrdngr25/src/scripts/base_features/train_extract_isvae.py", line 412, in <module>
    sys.exit(main())
  File "/home/mlin/repos/lrdngr25/src/scripts/base_features/train_extract_isvae.py", line 387, in main
    res_dict = extract(
  File "/home/mlin/repos/lrdbasefea/src/lrdbasefea/model/extract.py", line 696, in extract
    model, vae_metadata, loaded_snapshot, device = _prep_model(
  File "/home/mlin/repos/lrdbasefea/src/lrdbasefea/model/extract.py", line 74, in _prep_model
    model = compile_pytorch_model_to_tensorrt(
  File "/home/mlin/repos/lrdbasefea/src/lrdbasefea/model/extract_utils.py", line 107, in compile_pytorch_model_to_tensorrt
    compiled_model = trt.compile(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch_tensorrt/_compile.py", line 286, in compile
    exp_program = dynamo_trace(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch_tensorrt/dynamo/_tracer.py", line 83, in trace
    exp_program = export(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/__init__.py", line 368, in export
    return _export(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1035, in wrapper
    raise e
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1008, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/exported_program.py", line 128, in wrapper
    return fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1970, in _export
    return _export_for_training(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1035, in wrapper
    raise e
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1008, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/exported_program.py", line 128, in wrapper
    return fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1834, in _export_for_training
    export_artifact = export_func(  # type: ignore[operator]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 1283, in _strict_export_lower_to_aten_ir
    gm_torch_level = _export_to_torch_ir(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/export/_trace.py", line 662, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1569, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 574, in _fn
    return fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1380, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 547, in __call__
    return _compile(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 986, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 715, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 750, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1361, in transform_code_object
    transformations(instructions, code_options)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 662, in transform
    tracer.run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2868, in run
    super().run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1748, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 378, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 317, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 118, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 903, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3072, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3198, in inline_call_
    tracer.run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1658, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 378, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 317, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 118, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 903, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3072, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3198, in inline_call_
    tracer.run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1658, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 443, in call_function
    return tx.inline_user_function_return(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 903, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3072, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3198, in inline_call_
    tracer.run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1736, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 378, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 317, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 118, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 903, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3072, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3198, in inline_call_
    tracer.run()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1052, in run
    while self.step():
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 962, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1658, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 953, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2153, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2219, in wrap_fx_proxy_cls
    return _wrap_fx_proxy(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2315, in _wrap_fx_proxy
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2536, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2471, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2017, in wrap_fake_exception
    return fn()
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2472, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2604, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2586, in run_node
    return node.target(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/utils/_stats.py", line 21, in wrapper
    return fn(*args, **kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1276, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1816, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1377, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2392, in _dispatch_impl
    self.wrap_meta_outputs_with_default_device_logic(
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2514, in wrap_meta_outputs_with_default_device_logic
    return tree_map(wrap, r)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/utils/_pytree.py", line 991, in tree_map
    return treespec.unflatten(map(func, *flat_args))
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/utils/_pytree.py", line 830, in unflatten
    leaves = list(leaves)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2492, in wrap
    ) = FakeTensor._find_common_device(func, flat_args)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 890, in _find_common_device
    merge_devices(arg)
  File "/home/mlin/.conda/ngr/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 885, in merge_devices
    raise RuntimeError(
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method mul of type object at 0x72166cd90ec0>(*(FakeTensor(..., device='cuda:1', size=(32768, 1, 1, 1, 57)), FakeTensor(..., device='cuda:0', size=(1, 3, 1, 1, 57))), **{}):
Unhandled FakeTensor Device Propagation for aten.mul.Tensor, found two different devices cuda:1, cuda:0
```
