### ISSUE TITLE
🐛 [Bug] RuntimeError: [Error thrown at core/util/trt_util.cpp:320] Expected type to be true but got false

### ISSUE THREAD

**Issue by zewenli98** [pytorch/TensorRT#2815]
##  Bug Description

While running DLRM, got the error:
```
WARNING:torch_tensorrt.dynamo.backend.backends:TRT conversion failed on the subgraph. See trace above. Returning GraphModule forward instead.
Traceback (most recent call last):
  File "/home/scratch.zewenl_sw/docker_workspace/TRT10/TensorRT/py/torch_tensorrt/dynamo/backend/backends.py", line 102, in _pretraced_backend
    trt_compiled = compile_module(
  File "/home/scratch.zewenl_sw/docker_workspace/TRT10/TensorRT/py/torch_tensorrt/dynamo/_compiler.py", line 402, in compile_module
    trt_module = convert_module(
  File "/home/scratch.zewenl_sw/docker_workspace/TRT10/TensorRT/py/torch_tensorrt/dynamo/conversion/_conversion.py", line 128, in convert_module
    return TorchTensorRTModule(
  File "/home/scratch.zewenl_sw/docker_workspace/TRT10/TensorRT/py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py", line 96, in __init__
    self.engine = torch.classes.tensorrt.Engine(
RuntimeError: [Error thrown at core/util/trt_util.cpp:320] Expected type to be true but got false
Unsupported TensorRT data type Unknown Data Type
```
It uses C++ runtime by default, which causes this error. If running with `use_python_runtime=True`, the error will disappear.

## To Reproduce
In https://github.com/pytorch/benchmark,
```
python run.py dlrm --precision fp16 -d cuda -t eval --backend torch_trt --bs 3 --truncate_long_and_double --ir torch_compile
```

**Comment by narendasan** [comment]
@zewenli98 can you post the logs?

**Comment by zewenli98** [comment]
It disappeared in the latest main branch and nightly pytorch. Don't know the reason. Will reopen once pops up
