### ISSUE TITLE
🐛 [Bug] Nightly import fails

### ISSUE THREAD

**Issue by laikhtewari** [pytorch/TensorRT#2820]
##  Bug Description

Installed nightly and got OSError: libnvinfer_plugin.so.10: cannot open shared object file: No such file or directory

## To Reproduce

```
pip install -U --pre torch_tensorrt --index-url https://download.pytorch.org/whl/nightly/cu121
python3 -c "import torch_tensorrt"
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ltewari/scratch/miniconda3/envs/nightly/lib/python3.9/site-packages/torch_tensorrt/__init__.py", line 102, in <module>
    _register_with_torch()
  File "/home/ltewari/scratch/miniconda3/envs/nightly/lib/python3.9/site-packages/torch_tensorrt/__init__.py", line 96, in _register_with_torch
    torch.ops.load_library(trtorch_dir + "/lib/libtorchtrt.so")
  File "/home/ltewari/scratch/miniconda3/envs/nightly/lib/python3.9/site-packages/torch/_ops.py", line 1242, in load_library
    ctypes.CDLL(path)
  File "/home/ltewari/scratch/miniconda3/envs/nightly/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvinfer_plugin.so.10: cannot open shared object file: No such file or directory
```
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): torch-tensorrt==2.4.0.dev20240429+cu121
 - PyTorch Version (e.g. 1.0): torch==2.4.0.dev20240507+cu121
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip (nightly)
 - Build command you used (if compiling from source): NA
 - Are you using local sources or building from archives: NA
 - Python version: Python 3.9.18
 - CUDA version:  12.4 
 - GPU models and configuration: H100 PCIe
 - Any other relevant information:

**Comment by narendasan** [comment]
@laikhtewari do you have tensorrt installed?

**Comment by laikhtewari** [comment]
Looks like it, I have tensorrt==8.6.1.post1
Shouldn't that be installed automatically as a dependency of torch_tensorrt?
