### ISSUE TITLE
❓ [Question] How to deal with this error: AssertionError: cuda_ext_fp8 could not be imported. E4M3 quantization requires CUDA and cuda_ext_fp8

### ISSUE THREAD

**Issue by zk1009** [pytorch/TensorRT#3024]
## ❓ Question

When I run the TensorRT/examples/dynamo/vgg16_fp8_ptq.py  
AssertionError: cuda_ext_fp8 could not be imported. E4M3 quantization requires CUDA and cuda_ext_fp8

## What you have already tried

I transfer the cuda version:11.8/12.1/12.2，it doesn't work

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version : 2.3.1
 - CPU Architecture: Core
 - OS : wsl ubuntu
 - How you installed PyTorch : pip
 - Python version: 3.10
 - CUDA version: 12.1
 - I build conda env by these comands: 
 conda create -n tensorrt python==3.10
 pip install torch torchvision torch-tensorrt tensorrt
 pip install nvidia-modelopt

## Full error reporting

Traceback (most recent call last):
  File "/home/kun/code/YOLOv6/tools/quantization/vgg16_fp8.py", line 106, in <module>
    trt_model = torchtrt.dynamo.compile(
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch_tensorrt/dynamo/_compiler.py", line 227, in compile
    trt_gm = compile_module(gm, inputs, settings)
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch_tensorrt/dynamo/_compiler.py", line 394, in compile_module
    submodule_outputs = submodule(
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.35", line 6, in forward
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/home/kun/miniconda3/envs/tensorrt/lib/python3.10/site-packages/modelopt/torch/quantization/tensor_quant.py", line 49, in scaled_e4m3_impl
    assert (
AssertionError: cuda_ext_fp8 could not be imported. E4M3 quantization requires CUDA and cuda_ext_fp8.

**Comment by Danielohayon** [comment]
Had the same problem. Building the image with TensorRT-Model-Optimizer's [Dockerfile](https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/docker/Dockerfile) solved it for me.

**Comment by peri044** [comment]
@zk1009 Can you check if the modelopt library is installed correctly ? How did you install it ? Using the docker image (as suggested above) might help.

**Comment by lanluo-nvidia** [comment]
I can confirm I had the same issue when I run directly on my linux workstation, 
it is due to failed to load the modelopt_cuda_ext_fp8 hence it reported:
cuda_ext_fp8 could not be imported. E4M3 quantization requires CUDA and cuda_ext_fp8

If I use [NVIDIA NGC PyTorch container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags) with Model Optimizer torch, torch_tensorrt pre-installed, it is working.

```
docker run --gpus all -it --shm-size 20g --rm -v$(pwd):/workspace/TensorRT  nvcr.io/nvidia/pytorch:24.07-py3  bash
# since this docker container has a slightly older modelopt 0.13.0, upgrade to the latest 0.15.0
python -m pip install "nvidia-modelopt[all]~=0.15.0" --extra-index-url https://pypi.nvidia.com/
python dynamo/vgg16_fp8_ptq.py --batch-size 128 --ckpt int8/training/vgg16/vgg16_ckpts/ckpt_epoch20.pth
```
