### ISSUE TITLE
🐛 [Bug] Creating `torch.tensor` from another tensor throws  `RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument`

### ISSUE THREAD

**Issue by chaoz-dev** [pytorch/TensorRT#907]
##  Bug Description
Attempting to create a `torch.tensor` using another `tensor` as the first input argument causes the following runtime error:
```
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument
```

This is likely due to the converter not supporting this specific method signature, as the following is also output:
```
ERROR: [Torch-TensorRT] - Unsupported operator: aten::FloatImplicit(Tensor a) -> (float)
  File "/scripts/tensor.py", line 22
    def forward(self, a):
        return torch.tensor(a)
               ~~~~~~~~~~~~ <--- HERE


ERROR: [Torch-TensorRT] - Unsupported operator: aten::tensor.float(float t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor)
  File "/scripts/tensor.py", line 22
    def forward(self, a):
        return torch.tensor(a)
               ~~~~~~~~~~~~ <--- HERE
```

## To Reproduce
Run the following:
```
  import torch    
  import torch_tensorrt as torchtrt    
      
      
  import torch_tensorrt.logging as logging    
      
  logging.set_reportable_log_level(logging.Level.Warning)    
      
  torch.manual_seed(0)    
      
  DEVICE = torch.device("cuda:0")    
  SHAPE = (1, 2)    
      
      
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()    
      
      def forward(self, a):    
          return torch.tensor(a)    
      
      
  if __name__ == "__main__":    
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)    
      
      model = Model().eval().to(DEVICE)    
      out = model(tensor)    
      print(f'Model: {out}')    
      
      model_trt = torchtrt.compile(    
          model,    
          inputs=[    
              torchtrt.Input(shape=SHAPE),    
          ],    
          enabled_precisions={torch.float},    
      )    
      out_trt = model(tensor)    
      print(f'Model TRT: {out_trt}')    
      
      assert torch.max(torch.abs(out - out_trt)) < 1e-6    
```

This will output the following: 
```
root@05bae625cea6:/workspace# python /scripts/tensor.py
/scripts/tensor.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(a)
Model: tensor([[-0.9247, -0.4253]], device='cuda:0')
WARNING: [Torch-TensorRT] - Cannot infer input type from calcuations in graph for input a.1. Assuming it is Float32. If not, specify input type explicity
ERROR: [Torch-TensorRT] - Method requested cannot be compiled by Torch-TensorRT.TorchScript.
Unsupported operators listed below:
  - aten::tensor.float(float t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor)
  - aten::FloatImplicit(Tensor a) -> (float)
You can either implement converters for these ops in your application or request implementation
https://www.github.com/nvidia/Torch-TensorRT/issues

In Module:

ERROR: [Torch-TensorRT] - Unsupported operator: aten::FloatImplicit(Tensor a) -> (float)
  File "/scripts/tensor.py", line 22
    def forward(self, a):
        return torch.tensor(a)
               ~~~~~~~~~~~~ <--- HERE


ERROR: [Torch-TensorRT] - Unsupported operator: aten::tensor.float(float t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor)
  File "/scripts/tensor.py", line 22
    def forward(self, a):
        return torch.tensor(a)
               ~~~~~~~~~~~~ <--- HERE


WARNING: [Torch-TensorRT] - Input type for doing shape analysis could not be determined, defaulting to F32
Traceback (most recent call last):
  File "/scripts/tensor.py", line 32, in <module>
    model_trt = torchtrt.compile(
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/scripts/tensor.py", line 22, in forward
    def forward(self, a):
        return torch.tensor(a)
               ~~~~~~~~~~~~ <--- HERE
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument
```

## Expected behavior
A deep copy of the torch tensor should be returned (as per https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor), either using the TRT converter or fallback if the converter is not available.

## Environment
Run using PyTorch NGC containers `21.11-py3` and `22.02-py3` on Ubuntu 18.04 x86-64.

## Additional context

This might also fall under "Feature Request" as it appears to be missing functionality for the `torch.tensor` converter, but I'll file as a bug since it's erroneously causing an runtime error as the non-TRT version appears to run correctly. 

This is also a minor issue, as `torch.clone` appears to work, so this is a non-blocker.

**Comment by narendasan** [comment]
I want to say that this is an issue with TorchScript honestly. I am not sure why TorchScript would expect this to do `Tensor->Float->Tensor`. What does the graph look like? (Should be visible with debug level logging). Also if you trace this explicitly how does the graph change and does it work?

**Comment by narendasan** [comment]
Also it would be worth trying this after scripting before torchtrt compilation as well to verify the graph is valid

**Comment by peri044** [comment]
Graph is this 
```
 Segment Block @0:
    Target: Torch

    Graph: graph(%a.1 : Tensor):
  %4 : bool = prim::Constant[value=0]()
  %3 : NoneType = prim::Constant()
  %0 : float = aten::FloatImplicit(%a.1) # chao.py:20:13
  %2 : Tensor = aten::tensor(%0, %3, %3, %4) # chao.py:20:13
  return ()
```
The error comes from shape analysis with dummy input run. Code line : https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/partitioning/shape_analysis.cpp#L91 
```
 def forward(self, a):
      return torch.tensor(a)
             ~~~~~~~~~~~~ <--- HERE
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument
```

**Comment by narendasan** [comment]
aten::tensor.float expects a float scalar. Why is shape_analysis producing unsupported operator error?

**Comment by narendasan** [comment]
@bowang007 Can you take a look as well?

**Comment by bowang007** [comment]
I don't think it fails because of shape_analysis. I got the same error when I tried to run it by torchscript c++ APIs.

**Comment by bowang007** [comment]
TorchTRT does nothing in this small model you provided.
The entire model will be fallback to torch in fact. And it fails when TorchTRT tries to run this small model in torchscript. 
That's why I'm getting same error when I run it using torchscript.

**Comment by chaoz-dev** [comment]
Closing this ticket for now, as in the course of trying to make a more complex model to test this issue, I wasn't able to come up with a use case that made sense; this issue will still occur with more complex models, but the specific issue is passing in a tensor as described... which can be side-stepped by using other ops.
