### ISSUE TITLE
 ❓[Question] RuntimeError: [Error thrown at core/conversion/converters/impl/select.cpp:236] Expected const_layer to be true but got false

### ISSUE THREAD

**Issue by pupumao** [pytorch/TensorRT#936]
## ❓ Question

when i convert jit model, got the error
this is my forward code: 
input `x` shape is `(batch, 6, height, width)`, first step is to split `x` into two tensors, but failed
```
    def forward(self, x):
        fg = x[:,0:3,:,:]   ## this line got error
        bg = x[:,3:,:,:]
        
        fg = self.backbone(fg)
        bg = self.backbone(bg)
        out = self.heads(fg, bg)
        return out
```
complete traceback:
```
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 3: [network.cpp::addConstant::1052] Error Code 3: Internal Error (Parameter check failed at: optimizer/api/network.cpp::addConstant::1052, condition: !weights.values == !weights.count
)
Traceback (most recent call last):
  File "model_converter.py", line 263, in <module>
    engine = get_engine(model_info.trt_engine_path, calib, int8_mode=int8_mode, optimize_params=optimize_params)
  File "model_converter.py", line 173, in get_engine
    return build_engine(max_batch_size)
  File "model_converter.py", line 95, in build_engine
    return build_engine_from_jit(max_batch_size)
  File "model_converter.py", line 80, in build_engine_from_jit
    tensorrt_engine_model = torch_tensorrt.ts.convert_method_to_trt_engine(traced_model, "forward", **compile_settings)
  File "/usr/local/lib/python3.6/dist-packages/torch_tensorrt/ts/_compiler.py", line 211, in convert_method_to_trt_engine
    return _C.convert_graph_to_trt_engine(module._c, method_name, _parse_compile_spec(compile_spec))
RuntimeError: [Error thrown at core/conversion/converters/impl/select.cpp:236] Expected const_layer to be true but got false
Unable to create constant layer from node: %575 : Tensor = aten::slice(%570, %13, %12, %14, %13) # /data/small_detection/centernet_pytorch_small_detection/models/low_freeze_comb_net.py:455:0
```

## What you have already tried

try use `fg, bg = x.split(int(x.shape[1] // 2), dim=1)` instead of `fg = x[:,0:3,:,:]` and `bg = x[:,3:,:,:]` but got convert error for op not support 

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.4.0
 - CPU Architecture: arm (nx)
 - OS (e.g., Linux):
 - How you installed PyTorch: docker of nvidia l4t
 - Python version: 3.6.9
 - CUDA version: 10.2.300
 - Tensorrt version: 8.0.1.6

**Comment by narendasan** [comment]
What version of Torch TRT are you using?

**Comment by pupumao** [comment]
> What version of Torch TRT are you using?

8.0.1.6

**Comment by narendasan** [comment]
Sorry not TensorRT, Torch-TensorRT?
