### ISSUE TITLE
🐛 [Bug] Encountered bug when lowering `aten::to`

### ISSUE THREAD

**Issue by Njuapp** [pytorch/TensorRT#954]
##  Bug Description

The lowering pass for `aten::to` could cause unexpected results. 
The error is as follows:
```bash
Successfully load torch model:
def forward(self,
    x: Tensor,
    y: Tensor) -> Tensor:
  basenet = self.basenet
  _0 = torch.to((basenet).forward(x, ), dtype=6, layout=0, device=torch.device("cuda:0"))
  return _0

TRTorch {self.trt_dtype} compile begin >>>
WARNING: [Torch-TensorRT] - Dilation not used in Max pooling converter
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    trt_ts_module = torch_tensorrt.compile(torch_script_module, **compile_settings)
  File "/opt/conda/lib/python3.7/site-packages/torch_tensorrt/_compile.py", line 115, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_tensorrt/ts/_compiler.py", line 116, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/util/trt_util.cpp:283] Expected type to be true but got false
Unsupported ATen data type Byte
```

## To Reproduce

```cpp
import torch
import math
import numpy as np
from torchvision import models

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        """ Base network """
        self.basenet = models.resnet50(pretrained=True)
        self.basenet.fc = torch.nn.Identity()

    def forward(self, x, y, test=True):
        """ Base network """
        x = self.basenet(x)
        return x.to(y.device)

model = Net()
model = model.eval()
model = model.cuda()

input = np.zeros((1, 3, 224, 224)).astype(np.float32)
label = torch.ones(1).int().cuda()
input = torch.from_numpy(input).cuda()
output = model(input, label)

torch_script_module = torch.jit.trace(model, (input, label))
torch.jit.save(torch_script_module, "torch_script_module.ts")
import torch_tensorrt 
torch_tensorrt.logging.set_reportable_log_level(torch_tensorrt.logging.Level.Graph)

import torch
torch_script_module = torch.jit.load("torch_script_module.ts", map_location='cuda').eval()
        
print('Successfully load torch model:')
trt_dtype = torch.float16
            #self.trt_dtype = torch.float32

compile_settings = {
    "inputs": [torch_tensorrt.Input(
        shape=[1, 3, 224, 224],  # TODO: depends on the model size
        dtype=torch.float32,  # Datatype of input tensor. Allowed options torch.(float|half|int8|int32|bool)
    ),
    torch_tensorrt.Input(
        shape=[1],
        dtype=torch.int32
    )],
    "require_full_compilation": False,
    "enabled_precisions": {torch.float32},  # Run with FP16
    "truncate_long_and_double": True,
}

print(torch_script_module.code)
print("TRTorch {self.trt_dtype} compile begin >>>")
trt_ts_module = torch_tensorrt.compile(torch_script_module, **compile_settings)

torch_script_output = torch_script_module(input, label)
trt_ts_output = trt_ts_module(input, label)
diff = abs(torch_script_output - trt_ts_output).mean()
print('Diff between torchscript output and trt_ts_module output is {:.6f}'.format(diff))

```

## Expected behavior

Compilation should go smoothly without error, and numerical difference shall be negligible.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.1.0a0+ba9f730f
 - PyTorch Version (e.g. 1.0): 1.10.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7
 - CUDA version: 11.3
 - GPU models and configuration: A100
 - TensorRT version: 8.2.2.1

**Comment by bowang95** [comment]
Hi @Njuapp, I found this bug this week too in this issue #941 , it seems that we should delete the lowering pass for reduce_to.

**Comment by bowang95** [comment]
Hi @Njuapp , could you please try if this PR #958  can fix your problem?

**Comment by bowang007** [comment]
closing per #958
