### ISSUE TITLE
❓ [Question] How do you fix "broadcast dimensions must be conformable"? 

### ISSUE THREAD

**Issue by dav-ell** [pytorch/TensorRT#961]
## ❓ Question

I'm converting my (EfficientDet) model using `torch_tensorrt.compile` like so, after having successfully torchscript'ed it and verified that the output is the same as the non-torchscripted version:

```python
trt_module = torch_tensorrt.compile(scripted_model, inputs=[torch.ones(1, 3, 512, 512)], enabled_precisions={torch.half})
```

When running the above, I'm getting this error:

```python
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer %46481 : Tensor = aten::add(%46424, %46480, %self.model.blocks.1) # /home/user/model.py:189:41: broadcast dimensions must be conformable)
```

The offending line is:

```python
p5_up = self.conv5_up(self.swish(weight[0] * p5_in + weight[1] * self.p5_upsample(p6_up)))
```

where `weight` is a two-element tensor. 

## What you have already tried

When broken up, the error happens more specifically with the add:

```python
weight_p5_in = weight[0] * p5_in
weight_p5_upsample = weight[1] * self.p5_upsample(p6_up)
weight_swish_add = weight_p5_in + weight_p5_upsample # error happens here
weight_swish = self.swish(weight_swish_add)
p5_up = self.conv5_up(weight_swish)
```

The shapes of both `weight_p5_in` and `weight_p5_upsample` are `[1, 64, 16, 16]`, so it can't be the shapes that are the problem. Furthermore, the line before it is very similar and has no error:

```
p6_up = self.conv6_up(self.swish(weight[0] * p6_in + weight[1] * self.p6_upsample(p7_in)))
```

I took a look at the values and didn't see anything fishy. I'm pretty much at a loss of what else to look at. 

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.11.0a0+17540c5
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): NGC PyTorch container, nvcr.io/nvidia/pytorch:22.02-py3
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.12
 - CUDA version: 11.6
 - GPU models and configuration: Quadro RTX 5000
 - Any other relevant information: Torch-TensorRT version 1.1.0a0

## Additional context

I was under the impression that any model that is `torch.jit.script()`able is able to be converted using Torch-TensorRT. That has not been the case for me, this is actually the second problem I'm facing when converting my `torch.jit.script()`ed model after having spent a while fixing the first issue (dealing with math.ceil() not being supported). Could I perhaps be using the wrong API?

**Comment by narendasan** [comment]
Can you provide a repro script or share the debug logs? Usually we print out what output tensor shapes are from ops, which can help show what is going on.

**Comment by dav-ell** [comment]
Attempting to make a repro script but stuck on a different issue now...

```python
import torch_tensorrt
print(torch_tensorrt.__version__)

import torch
import torch.nn as nn
from torch.nn import functional as F
print(torch.__version__)
import math
from typing import List


class Conv2dStaticSamePadding(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, bias=True, groups=1, dilation=1, **kwargs):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size, stride=stride,
                              bias=bias, groups=groups)
        self.stride = self.conv.stride
        self.kernel_size = self.conv.kernel_size
        self.dilation = self.conv.dilation

        if isinstance(self.stride, int):
            self.stride = [self.stride] * 2
        elif len(self.stride) == 1:
            self.stride = [self.stride[0]] * 2

        if isinstance(self.kernel_size, int):
            self.kernel_size = [self.kernel_size] * 2
        elif len(self.kernel_size) == 1:
            self.kernel_size = [self.kernel_size[0]] * 2

    def forward(self, x):
        h, w = x.shape[2], x.shape[3]
        s1, s0 = self.stride[1], self.stride[0]
        k1, k0 = self.kernel_size[1], self.kernel_size[0]

        extra_h = (self.divide_ceil(w, s1) - 1) * s1 - w + k1
        extra_v = (self.divide_ceil(h, s0) - 1) * s0 - h + k0
        
        left = math.floor(torch.div(extra_h, 2))
        right = extra_h - left
        top = math.floor(torch.div(extra_v, 2))
        bottom = extra_v - top

        x = F.pad(x, [left, right, top, bottom])

        x = self.conv(x)
        return x

    def divide_ceil(self, a: int, b: int) -> int:
        return -(-a // b)

class SeparableConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels=None, norm=True, activation=False, onnx_export=False):
        super(SeparableConvBlock, self).__init__()
        if out_channels is None:
            out_channels = in_channels

        self.depthwise_conv = Conv2dStaticSamePadding(in_channels, in_channels,
                                                      kernel_size=3, stride=1, groups=in_channels, bias=False)
        self.pointwise_conv = Conv2dStaticSamePadding(in_channels, out_channels, kernel_size=1, stride=1)

        self.norm = norm
        # Warning: pytorch momentum is different from tensorflow's, momentum_pytorch = 1 - momentum_tensorflow
        self.bn = nn.BatchNorm2d(num_features=out_channels, momentum=0.01, eps=1e-3)

        self.activation = activation

    def forward(self, x):
        x = self.depthwise_conv(x)
        x = self.pointwise_conv(x)

        if self.norm:
            x = self.bn(x)

        return x
    
class Swish(nn.Module):
    def forward(self, x):
        return x * torch.sigmoid(x)
    
class TestBrokenStuff(nn.Module):
    def __init__(self):
        super().__init__()
        self.epsilon = 1e-4
        
        self.p6_w1 = nn.Parameter(torch.ones(2), requires_grad=True)
        self.p6_w1_relu = nn.ReLU()
        self.p5_w1 = nn.Parameter(torch.ones(2), requires_grad=True)
        self.p5_w1_relu = nn.ReLU()
        
        self.conv5_up = SeparableConvBlock(64, onnx_export=True)
        self.conv6_up = SeparableConvBlock(64, onnx_export=True)
        self.swish = Swish()
        self.p6_upsample = nn.Upsample(scale_factor=2, mode='nearest')
        self.p5_upsample = nn.Upsample(scale_factor=2, mode='nearest')
        
    def forward(self, p5_in, p6_in, p7_in):
        # Weights for P6_0 and P7_0 to P6_1
        p6_w1 = self.p6_w1_relu(self.p6_w1)
        weight = p6_w1 / (torch.sum(p6_w1, dim=0) + self.epsilon)
        # Connections for P6_0 and P7_0 to P6_1 respectively
        p6_up = self.conv6_up(self.swish(weight[0] * p6_in + weight[1] * self.p6_upsample(p7_in)))

        # Weights for P5_0 and P6_1 to P5_1
        p5_w1 = self.p5_w1_relu(self.p5_w1)
        weight = p5_w1 / (torch.sum(p5_w1, dim=0) + self.epsilon)
        # Connections for P5_0 and P6_1 to P5_1 respectively
        weight_p5_in = weight[0] * p5_in
        weight_p5_upsample = weight[1] * self.p5_upsample(p6_up)
        weight_swish_add = weight_p5_in + weight_p5_upsample
        weight_swish = self.swish(weight_swish_add)
        p5_up = self.conv5_up(weight_swish)
        
        return p6_up, p5_up
    
model = TestBrokenStuff()
dummy_input = (torch.ones(1, 64, 16, 16), torch.ones(1, 64, 8, 8), torch.ones(1, 64, 4, 4))
dummy_out = model(*dummy_input)
print("nonscripted", [out.shape for out in dummy_out])
scripted_model = torch.jit.script(model)
dummy_out = scripted_model(*dummy_input)
print("scripted", [out.shape for out in dummy_out])

trt_model = torch_tensorrt.compile(scripted_model, 
    inputs= [torch_tensorrt.Input(dummy_input[0].shape), 
             torch_tensorrt.Input(dummy_input[1].shape), 
             torch_tensorrt.Input(dummy_input[2].shape)],
)
```

outputs

```python
1.1.0a0
1.11.0a0+17540c5
nonscripted [torch.Size([1, 64, 8, 8]), torch.Size([1, 64, 16, 16])]
scripted [torch.Size([1, 64, 8, 8]), torch.Size([1, 64, 16, 16])]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [15], in <module>
    121 dummy_out = scripted_model(*dummy_input)
    122 print("scripted", [out.shape for out in dummy_out])
--> 124 trt_model = torch_tensorrt.compile(scripted_model, 
    125     inputs= [torch_tensorrt.Input(dummy_input[0].shape), 
    126              torch_tensorrt.Input(dummy_input[1].shape), 
    127              torch_tensorrt.Input(dummy_input[2].shape)],
    128 )

File /opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py:97, in compile(module, ir, inputs, enabled_precisions, **kwargs)
     92         logging.log(
     93             logging.Level.Info,
     94             "Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript"
     95         )
     96         ts_mod = torch.jit.script(module)
---> 97     return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
     98 elif target_ir == _IRType.fx:
     99     raise RuntimeError("fx is currently not supported")

File /opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py:119, in compile(module, inputs, device, disable_tf32, sparse_weights, enabled_precisions, refit, debug, strict_types, capability, num_min_timing_iters, num_avg_timing_iters, workspace_size, max_batch_size, calibrator, truncate_long_and_double, require_full_compilation, min_block_size, torch_executed_ops, torch_executed_modules)
     91     raise ValueError(
     92         "require_full_compilation is enabled however the list of modules and ops to run in torch is not empty. Found: torch_executed_ops: "
     93         + torch_executed_ops + ", torch_executed_modules: " + torch_executed_modules)
     95 spec = {
     96     "inputs": inputs,
     97     "device": device,
   (...)
    116     }
    117 }
--> 119 compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
    120 compiled_module = torch.jit._recursive.wrap_cpp_module(compiled_cpp_mod)
    121 return compiled_module

RuntimeError: Unknown type bool encountered in graph lowering. This type is not supported in ONNX export.
```

**Comment by dav-ell** [comment]
Apologies, I forgot `model.eval()`. After doing that, it just hangs...

**Comment by dav-ell** [comment]
Correction, it has a segmentation fault. See attached log.

[logs.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8420240/logs.txt)

**Comment by dav-ell** [comment]
I think I discovered the issue. It seems that using nn.Upsample causes a segmentation fault for unknown reasons. It also looks like F.upsample has the same issue. 

@narendasan any ideas? Perhaps this could be related to my original problem, though it doesn't make sense why my first error (not comformable) wasn't also a segfault.

**Comment by dav-ell** [comment]
Potentially related to https://github.com/pytorch/pytorch/issues/27376 and https://github.com/onnx/onnx-tensorrt/issues/361#issuecomment-576004279.

**Comment by dav-ell** [comment]
I was able to get the debug logs you're looking for, and the error seems to be an off-by-one issue (see attached for full log).

```python
DEBUG: [Torch-TensorRT] - ITensor shape: [1, 64, 16, 249]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - ITensor shape: [1, 64, 16, 248]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer %32975 : Tensor = aten::add(%32950, %32974, %self.backbone_net.model._blocks.0.expand_ratio.1) # /home/user/models/efficientdet/bifpn.py:180:41: broadcast dimensions must be conformable)
DEBUG: [Torch-TensorRT] - Output tensor shape: []
```

The conversion to TensorRT must break because something is being evaluated differently than torchscript...

[logs_debug.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8421313/logs_debug.txt)

**Comment by narendasan** [comment]
Hmm yeah seems like the `1, 64, 16, 249` is derived from a series of batch norms and `1, 64, 16, 248` from upsample nearest, that definitely narrows down where to look.

**Comment by dav-ell** [comment]
Yeah, trying to find a minimal reproducible script now. Is there a way to make the conversion fall back to PyTorch for these kind of issues, or is fixing this issue, for example, part of the Torch-TensorRT conversion process?

**Comment by dav-ell** [comment]
By adding `torch_executed_ops=["aten::ceil"]`, I can get farther along. Like so:

```python
trt_model = torch_tensorrt.ts.compile(scripted_model, 
                                    inputs=[torch.ones(1, 3, 512, 512)], 
                                    enabled_precisions={torch.half},
                                    torch_executed_ops=[
                                        "aten::ceil"
                                        ]
                                    )
``` 

Though then I get stuck with another error.

```python
Traceback (most recent call last):
  File "convert.py", line 54, in <module>
    trt_model = torch_tensorrt.ts.compile(scripted_model, 
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: Expected Tensor but got Uninitialized
```

I don't see any errors that might help me with how to fix it, however. Log below.

[logs_full_debug.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8429543/logs_full_debug.txt)

**Comment by narendasan** [comment]
yes. You can explicitly specify operators to run in PyTorch using `torch_executed_ops`

**Comment by dav-ell** [comment]
I've been able to convert the most problematic part of my network (so far), but when performing inference it gives me a segmentation fault. @narendasan can you help with this at all? I'm now working on the PyTorch -> ONNX -> TensorRT route, because ONNX isn't giving me the same issues that Torch_TensorRT is.


[test_bifpn.py.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8476889/test_bifpn.py.txt)
[bifpn.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8476887/bifpn.txt)
[bifpn.trt.pth.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8476886/bifpn.trt.pth.txt)

**Comment by narendasan** [comment]
Hmm, I will take another pass on this once we wrap up this release cycle. I can replicate the segfault and it seems to be coming from PyTorch. From what I can tell the tensors we are getting passed in the engine execution op are malformed, so when we query for things from PyTorch like current device and data type we get null pointer dereference's within torch::Tensor.   

This is odd since our inference testing is passing which presumably does the same set of operations.

**Comment by Hodapp87** [comment]
@dav-ell I am encountering the same `RuntimeError: Unknown type bool encountered in graph lowering. This type is not supported in ONNX export.` error that is in your paste above, and at the same `compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))` line. Do you have any clue what was causing this problem for you, and how you were able to fix it? I saw your note on `model.eval()` but this had no effect for me.

I am on torch_tensorrt 1.1.0, torch 1.11.0+cu115. Both `torchtrtc` at the commandline and `torch_tensorrt.compile()` (from the original module, not the Torchscript one) produced this.

**Comment by Christina-Young-NVIDIA** [comment]
Naren needs to ask user to retest with latest codebase.
